server:
  port: 9564
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: omid@321
    url: jdbc:mysql://localhost:3306/tt?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: none